In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies = pd.read_csv(r'C:\Users\tahag\Desktop\movie-recommendation-system\data\raw\movies.csv')
ratings = pd.read_csv(r'C:\Users\tahag\Desktop\movie-recommendation-system\data\raw\ratings.csv')

In [3]:
ratings.head(5)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
df = pd.merge(ratings, movies, on= 'movieId')
df.head(5)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy

In [6]:
user_movie_matrix = pd.pivot_table(df, index='userId', columns='title', values='rating')
user_movie_matrix.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
zeze = user_movie_matrix.groupby('userId').value_counts()
zeze

Series([], Name: count, dtype: int64)

In [45]:
rated_movies_count_by_user = user_movie_matrix.loc[5].count()
rated_movies_count_by_user

44

In [7]:
user_movie_filled = user_movie_matrix.fillna(0)
user_movie_filled.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
user_similarity = cosine_similarity(user_movie_filled)

In [9]:
user_similarity.shape

(610, 610)

In [10]:
user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_movie_filled.index,
    columns=user_movie_filled.index
)

user_similarity_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [11]:
target_user = 1

In [12]:
similar_users = user_similarity_df[target_user].sort_values(ascending=False)
#kendisini listeden çıkar
similar_users = similar_users.drop(index = target_user)
similar_users = similar_users[similar_users > 0.30]
similar_users.head(10)

userId
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
45     0.327922
Name: 1, dtype: float64

In [13]:
target_user_ratings = user_movie_matrix.loc[target_user]
rated_movies = target_user_ratings[target_user_ratings.notna()].index

In [14]:
unrated_movies = user_movie_matrix.columns.difference(rated_movies)
len(unrated_movies)

9487

In [15]:
similar_users_ratings = user_movie_matrix.loc[similar_users.index]
similar_users_ratings.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
similar_users_df = similar_users.reset_index()
similar_users_df.columns = ['userId', 'similarity']
similar_users_df.head()

   userId  similarity
0     266    0.357408
1     313    0.351562
2     368    0.345127
3      57    0.345034
4      91    0.334727

In [17]:
similar_users_ratings_long = similar_users_ratings.stack().reset_index()
similar_users_ratings_long.columns = ['userId', 'title', 'rating']
similar_users_ratings_long.head()

   userId                         title  rating
0     266  2001: A Space Odyssey (1968)     5.0
1     266             Abyss, The (1989)     4.0
2     266              Airplane! (1980)     1.0
3     266                 Aliens (1986)     5.0
4     266           American Pie (1999)     1.0

In [18]:
similar_users_ratings_long = similar_users_ratings_long.merge(similar_users_df, on="userId")
similar_users_ratings_long.head()

   userId                         title  rating  similarity
0     266  2001: A Space Odyssey (1968)     5.0    0.357408
1     266             Abyss, The (1989)     4.0    0.357408
2     266              Airplane! (1980)     1.0    0.357408
3     266                 Aliens (1986)     5.0    0.357408
4     266           American Pie (1999)     1.0    0.357408

In [19]:
similar_users_ratings_long["weighted_rating"] = (
    similar_users_ratings_long["rating"] * similar_users_ratings_long["similarity"]
)

similar_users_ratings_long.head()

   userId                         title  rating  similarity  weighted_rating
0     266  2001: A Space Odyssey (1968)     5.0    0.357408         1.787039
1     266             Abyss, The (1989)     4.0    0.357408         1.429631
2     266              Airplane! (1980)     1.0    0.357408         0.357408
3     266                 Aliens (1986)     5.0    0.357408         1.787039
4     266           American Pie (1999)     1.0    0.357408         0.357408

In [20]:
candidate_movies = similar_users_ratings_long[
    similar_users_ratings_long["title"].isin(unrated_movies)
]
candidate_movies.head()

   userId                         title  rating  similarity  weighted_rating
0     266  2001: A Space Odyssey (1968)     5.0    0.357408         1.787039
2     266              Airplane! (1980)     1.0    0.357408         0.357408
3     266                 Aliens (1986)     5.0    0.357408         1.787039
4     266           American Pie (1999)     1.0    0.357408         0.357408
5     266           Analyze This (1999)     4.0    0.357408         1.429631

In [21]:
recommendation_scores = candidate_movies.groupby("title").agg({
    "weighted_rating": "sum",
    "similarity": "sum"
})

In [22]:
recommendation_scores["recommendation_score"] = (
    recommendation_scores["weighted_rating"] / recommendation_scores["similarity"]
)

In [23]:
recommendation_scores = recommendation_scores.sort_values(
    by="recommendation_score", ascending=False
)

recommendation_scores.head(10)

,weighted_rating,similarity,recommendation_score
title,,,
Drugstore Cowboy (1989),3.213124,0.642625,5.0
Manhattan (1979),3.217535,0.643507,5.0
"Beastmaster, The (1982)",1.757808,0.351562,5.0
Denise Calls Up (1995),1.514441,0.302888,5.0
Eat Drink Man Woman (Yin shi nan nu) (1994),1.564213,0.312843,5.0
Stardust Memories (1980),1.564213,0.312843,5.0
Nobody's Fool (1994),1.564213,0.312843,5.0
Doctor Zhivago (1965),1.725171,0.345034,5.0
Old Boy (2003),1.576058,0.315212,5.0
"Spring, Summer, Fall, Winter... and Spring (Bom yeoreum gaeul gyeoul geurigo bom) (2003)",1.576058,0.315212,5.0

In [24]:
top_10_recommendations = recommendation_scores.head(10)
top_10_recommendations

,weighted_rating,similarity,recommendation_score
title,,,
Drugstore Cowboy (1989),3.213124,0.642625,5.0
Manhattan (1979),3.217535,0.643507,5.0
"Beastmaster, The (1982)",1.757808,0.351562,5.0
Denise Calls Up (1995),1.514441,0.302888,5.0
Eat Drink Man Woman (Yin shi nan nu) (1994),1.564213,0.312843,5.0
Stardust Memories (1980),1.564213,0.312843,5.0
Nobody's Fool (1994),1.564213,0.312843,5.0
Doctor Zhivago (1965),1.725171,0.345034,5.0
Old Boy (2003),1.576058,0.315212,5.0
"Spring, Summer, Fall, Winter... and Spring (Bom yeoreum gaeul gyeoul geurigo bom) (2003)",1.576058,0.315212,5.0

In [25]:
top_10_recommendations.index.tolist()

['Drugstore Cowboy (1989)',
 'Manhattan (1979)',
 'Beastmaster, The (1982)',
 'Denise Calls Up (1995)',
 'Eat Drink Man Woman (Yin shi nan nu) (1994)',
 'Stardust Memories (1980)',
 "Nobody's Fool (1994)",
 'Doctor Zhivago (1965)',
 'Old Boy (2003)',
 'Spring, Summer, Fall, Winter... and Spring (Bom yeoreum gaeul gyeoul geurigo bom) (2003)']

In [29]:
def user_based_recommender(target_user, user_movie_matrix, similarity_threshold=0.30, min_rating_count=2, top_n=10):
    # NaN'ları 0 yap
    user_movie_filled = user_movie_matrix.fillna(0)

    # cosine similarity
    user_similarity = cosine_similarity(user_movie_filled)

    user_similarity_df = pd.DataFrame(
        user_similarity,
        index=user_movie_filled.index,
        columns=user_movie_filled.index
    )

    # benzer kullanıcıları bul
    similar_users = user_similarity_df[target_user].sort_values(ascending=False)

    # kendisini çıkar
    similar_users = similar_users.drop(index=target_user)

    # threshold uygula
    similar_users = similar_users[similar_users > similarity_threshold]

    if similar_users.empty:
        return "Bu threshold ile benzer kullanıcı bulunamadı."

    # hedef kullanıcının izlediği filmler
    target_user_ratings = user_movie_matrix.loc[target_user]
    rated_movies = target_user_ratings[target_user_ratings.notna()].index

    # izlemediği filmler
    unrated_movies = user_movie_matrix.columns.difference(rated_movies)

    # benzer kullanıcıların ratingleri
    similar_users_ratings = user_movie_matrix.loc[similar_users.index]

    # similarity dataframe
    similar_users_df = similar_users.reset_index()
    similar_users_df.columns = ["userId", "similarity"]

    # long format
    similar_users_ratings_long = similar_users_ratings.stack().reset_index()
    similar_users_ratings_long.columns = ["userId", "title", "rating"]

    # similarity merge
    similar_users_ratings_long = similar_users_ratings_long.merge(similar_users_df, on="userId")

    # weighted rating
    similar_users_ratings_long["weighted_rating"] = (
        similar_users_ratings_long["rating"] * similar_users_ratings_long["similarity"]
    )

    # sadece hedef kullanıcının izlemediği filmler
    candidate_movies = similar_users_ratings_long[
        similar_users_ratings_long["title"].isin(unrated_movies)
    ]

    if candidate_movies.empty:
        return "Aday film bulunamadı."

    # skor hesapla
    recommendation_scores = candidate_movies.groupby("title").agg({
        "weighted_rating": "sum",
        "similarity": "sum",
        "rating": "count"
    })

    recommendation_scores["recommendation_score"] = (
        recommendation_scores["weighted_rating"] / recommendation_scores["similarity"]
    )

    recommendation_scores = recommendation_scores.rename(columns={"rating": "rating_count"})

    # minimum oy filtresi
    recommendation_scores = recommendation_scores[
        recommendation_scores["rating_count"] >= min_rating_count
    ]

    if recommendation_scores.empty:
        return "Filtrelerden sonra öneri kalmadı."

    # sırala
    recommendation_scores = recommendation_scores.sort_values(
        by="recommendation_score", ascending=False
    )

    return recommendation_scores.head(top_n)

In [34]:
user_based_recommender(target_user=5, user_movie_matrix=user_movie_matrix)

,weighted_rating,similarity,rating_count,recommendation_score
title,,,,
White Squall (1996),3.080488,0.616098,2,5.000000
Wallace & Gromit: The Best of Aardman Animation (1996),3.661502,0.732300,2,5.000000
Star Wars: Episode IV - A New Hope (1977),7.208396,1.474495,4,4.888722
Wallace & Gromit: A Close Shave (1995),5.612098,1.211434,3,4.632607
Aladdin and the King of Thieves (1996),2.879490,0.635968,2,4.527729
All Dogs Go to Heaven 2 (1996),2.879490,0.635968,2,4.527729
Flipper (1996),2.879490,0.635968,2,4.527729
Kids (1995),3.353770,0.746205,2,4.494434
Mystery Science Theater 3000: The Movie (1996),2.883489,0.645103,2,4.469814
Star Trek: First Contact (1996),7.842994,1.781163,5,4.403301